apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt-example"
spec:
  targets:
  - name: frontend
  origins:
  - jwt:
      issuer: "http://voravit.example.com:8080/auth/realms/example.com"
      jwksUri: "https://gitlab.com/workshop6/service-mesh/raw/master/keycloak/jwks.json"
  principalBinding: USE_ORIGIN
  # Get Cert from RHSSO
  # curl http://localhost:8080/auth/realms/example.com/protocol/openid-connect/certs
  