apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt-example"
spec:
  targets:
  - name: frontend
  origins:
  - jwt:
      issuer: "http://voravit.example.com:8080/auth/realms/example.com"
      #issuer: "testing@secure.istio.io"
      jwksUri: ""
  principalBinding: USE_ORIGIN
  # Get Cert from RHSSO
  # curl http://localhost:8080/auth/realms/example.com/protocol/openid-connect/certs
  # TOKEN=$(curl https://raw.githubusercontent.com/istio/istio/release-1.4/security/tools/jwt/samples/demo.jwt -s)