apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-v2
  labels:
    app: backend
    version: 2.0.0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        version: 2.0.0
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: backend
        image: quay.io/voravitl/backend-js:2.0.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "0.1"
            memory: 60Mi
          limits:
            cpu: "0.2"
            memory: 100Mi
        env:
          - name: BACKEND_URL
            value: https://httpbin.org/delay/5
        ports:
        - containerPort: 8080
